# @package hydra.launcher
_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
submitit_folder: ${hydra.sweep.dir}/.submitit/%j
timeout_min: 2880
gpus_per_node: 1
nodes: 1
mem_gb: 64
cpus_per_task: 8
partition: null
setup:
  - source $HOME/miniconda3/etc/profile.d/conda.sh
  - conda activate finetune
