# @package hydra.launcher
_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
submitit_folder: ${hydra.sweep.dir}/.submitit/%j
timeout_min: 360          # 6小时，debug 队列默认限制
gpus_per_node: 1
nodes: 1
mem_gb: 96                # RTX4090 每卡配 96GB 内存
cpus_per_task: 4          # 每卡配 4 核
partition: debug          # RTX4090 队列
setup:
  - source $HOME/miniconda3/etc/profile.d/conda.sh
  - conda activate finetune
