# @package hydra.launcher
_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
submitit_folder: ${hydra.sweep.dir}/.submitit/%j
timeout_min: 10080        # 7天
gpus_per_node: 1
nodes: 1
mem_gb: 190
cpus_per_task: 4
partition: q-hgpu-batch   # 只能用 sbatch，支持 H100/H800
setup:
  - source $HOME/miniconda3/etc/profile.d/conda.sh
  - conda activate finetune
